apiVersion: apps/v1
kind: Deployment
metadata:
  name: cuda
  labels:
    app: cuda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cuda
  template:
    metadata:
      labels:
        app: cuda
    spec:
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      hostPID: true
      containers:
        - name: cuda-sample-vector-add
          image: "nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda11.7.1-ubuntu20.04"
          command: ["/bin/bash", "-c", "--"]
          args:
            - while true; do /cuda-samples/vectorAdd; done
          resources:
            requests:
              nvidia.com/gpu: 1
              cpu: 100m
              memory: 128Mi
            limits:
              nvidia.com/gpu: 1
              cpu: 100m
              memory: 128Mi